export const productsMock = [
  {
    id: 1,
    name: 'Pantalón Chino Gabardina Azul Noche',
    price: 2750,
    description:
      'Combiná nuestro pantalón chino tanto con camisas como con chombas. Ideales para un look semi formal.',
    category: ['pantalones'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/9-6-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/10-6-600x941.jpg',
    ],
    color: 'azul',
    stock: 15,
    sale: false,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 2,
    name: 'Pantalón Chino Gabardina Beige Noche',
    price: 2750,
    description:
      'Combiná nuestro pantalón chino tanto con camisas como con chombas. Ideales para un look semi formal.',
    category: ['pantalones'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/19-3-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/20-3-600x749.jpg',
    ],
    color: 'beige',
    stock: 15,
    sale: true,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 3,
    name: 'Pantalón Chino Gabardina Negro Noche',
    price: 3200,
    description:
      'Combiná nuestro pantalón chino tanto con camisas como con chombas. Ideales para un look semi formal.',
    category: ['pantalones'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/13-5-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/14-4-600x767.jpg',
    ],
    color: 'negro',
    stock: 15,
    sale: false,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 4,
    name: 'Pantalón Chino Gabardina Gris Noche',
    price: 3100,
    description:
      'Combiná nuestro pantalón chino tanto con camisas como con chombas. Ideales para un look semi formal.',
    category: ['pantalones'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/11-5-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/12-5-600x950.jpg',
    ],
    color: 'gris',
    stock: 15,
    sale: true,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 5,
    name: 'Pantalón Chino Gabardina Bronce Noche',
    price: 3200,
    description:
      'Combiná nuestro pantalón chino tanto con camisas como con chombas. Ideales para un look semi formal.',
    category: ['pantalones'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/21-3-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/22-4-600x767.jpg',
    ],
    color: 'bronce',
    stock: 15,
    sale: false,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 6,
    name: 'Zapatillas camel',
    price: 5500,
    description: 'Calzado de base alta confeccionado en cuero ecológico.',
    category: ['zapatillas'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/1-2-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/2-2-600x600.jpg',
    ],
    color: 'camel',
    stock: 10,
    sale: true,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 7,
    name: 'Zapatillas blancas',
    price: 5500,
    description: 'Calzado de base alta confeccionado en cuero ecológico.',
    category: ['zapatillas'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/8-2-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/9-2-600x600.jpg',
    ],
    color: 'blanco',
    stock: 15,
    sale: false,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 8,
    name: 'Zapatillas negras',
    price: 5700,
    description: 'Calzado de base alta confeccionado en cuero ecológico.',
    category: ['zapatillas'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/4-2-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/5-2-600x600.jpg',
    ],
    color: 'negro',
    stock: 15,
    sale: true,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 9,
    name: 'Buzo Frisa Negro',
    price: 2000,
    description:
      'Uno de los ítems favoritos de esta temporada de invierno ’21. Son un abrigo de buena densidad, cómodo, suave por dentro y por fuera.',
    category: ['buzos'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/41-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/43-600x928.jpg',
    ],
    color: 'negro',
    stock: 20,
    sale: false,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 10,
    name: 'Buzo Frisa Verde',
    price: 2200,
    description:
      'Uno de los ítems favoritos de esta temporada de invierno ’21. Son un abrigo de buena densidad, cómodo, suave por dentro y por fuera.',
    category: ['buzos'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/35-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/36-600x949.jpg',
    ],
    color: 'verde',
    stock: 15,
    sale: true,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 11,
    name: 'Buzo Frisa Bordo',
    price: 3200,
    description:
      'Uno de los ítems favoritos de esta temporada de invierno ’21. Son un abrigo de buena densidad, cómodo, suave por dentro y por fuera.',
    category: ['buzos'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/38-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/40-600x1064.jpg',
    ],
    color: 'bordo',
    stock: 5,
    sale: false,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 12,
    name: 'Buzo Frisa Azul',
    price: 2200,
    description:
      'Uno de los ítems favoritos de esta temporada de invierno ’21. Son un abrigo de buena densidad, cómodo, suave por dentro y por fuera.',
    category: ['buzos'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/32-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/33-600x970.jpg',
    ],
    color: 'azul',
    stock: 5,
    sale: true,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 13,
    name: 'Canguro Mostaza',
    price: 4000,
    description: 'Buzo canguro jaspeado, con estampa, capucha y bolsillo.',
    category: ['canguros'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/03/24-3-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/03/24a-600x600.jpg',
    ],
    color: 'mostaza',
    stock: 30,
    sale: false,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 14,
    name: 'Canguro Lila',
    price: 3200,
    description: 'Buzo canguro jaspeado, con estampa, capucha y bolsillo.',
    category: ['canguros'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/03/23-3.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/03/23a-600x600.jpg',
    ],
    color: 'lila',
    stock: 10,
    sale: true,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 15,
    name: 'Chaqueta ladrillo',
    price: 6000,
    description: 'Chaquetas de gabardina, quedan geniales y son súper cómodas.',
    category: ['chaquetas'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/04/74-1-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/04/73-1-600x866.jpg',
    ],
    color: 'ladrillo',
    stock: 15,
    sale: false,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 16,
    name: 'Chaqueta Azul',
    price: 6000,
    description: 'Chaquetas de gabardina, quedan geniales y son súper cómodas.',
    category: ['chaquetas'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/03/25-3-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/03/27-3-600x600.jpg',
    ],
    color: 'azul',
    stock: 15,
    sale: true,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 17,
    name: 'Remera blanca',
    price: 1000,
    description: 'Remera básica con puños y cuello combinados en gross.',
    category: ['remeras'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/Capa-0-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/58-600x880.jpg',
    ],
    color: 'blanco',
    stock: 15,
    sale: false,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
  {
    id: 18,
    name: 'Remera Beige',
    price: 1000,
    description: 'Remera básica con puños y cuello combinados en gross.',
    category: ['remeras'],
    images: [
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/26-600x600.jpg',
      'https://orsobianco.com.ar/wp-content/uploads/2021/05/26-600x600.jpg',
    ],
    color: 'beige',
    stock: 15,
    sale: true,
    sizeAvailable: ['xs', 's', 'm', 'l', 'xl'],
  },
];
